baseurl = "/"
title = "Lógica Ladeira Abaixo (LLA)"
languageCode = "pt-br"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

#[Author] # Used in authorbox
#  name = "Henrique Antunes"
#  bio = "" 
#  avatar = "images/HA.jpg"
#
[Params]
  subtitle = "Grupo de Pesquisa em Lógica e Metafísica" # Subtitle of your site. Used in site header
  description = "Grupo de Pesquisa em Lógica e Metafísica" # Site description. Used in meta description
  copyright = "LLA" # Footer copyright holder, otherwise will use site title
  opengraph = false # Enable OpenGraph if true
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02/01/2006" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.logo]
  # image = "images/lla-logo.jpg" # Logo image. Path relative to "static"
  title = "Lógica Ladeira Abaixo" # Logo title, otherwise will use site title
  subtitle = "Grupo de pesquisa em lógica e metafísica vinculado ao departamento de filosofia da Universidade Federal de Ouro Preto" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

#[Params.widgets.social]
# # Enable parts of social widget
#  facebook = "username"
#  twitter = "username"
#  instagram = "username"
#  linkedin = "username"
#  telegram = "username"
#  email = "email@example.com"
	
[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1
  
[[menu.main]]
  name = "Notícias"
  url = "/noticias"
  weight = 2

[[menu.main]]
  name = "Sobre"
  url = "/sobre"
  weight = 3

[[menu.main]]
  name = "Membros"
  url = "/membros/"
  weight = 4

[[menu.main]]
  name = "Reuniões"
  url = "/reunioes/"
  weight = 5

[[menu.main]]
  name = "Eventos"
  url = "/eventos/"
  weight = 6

[[menu.main]]
  name = "Galeria" 
  url = "/galeria/"
  weight = 7

[[menu.main]]
  name = "Contato" 
  url = "/contato"
  weight = 8
